-- Misafir sipariş: userId opsiyonel; teslimat/fatura snapshot alanları
ALTER TABLE `Order` DROP FOREIGN KEY `Order_userId_fkey`;

ALTER TABLE `Order` MODIFY `userId` INTEGER NULL;

ALTER TABLE `Order` ADD COLUMN `guestEmail` VARCHAR(255) NULL;
ALTER TABLE `Order` ADD COLUMN `guestPhone` VARCHAR(40) NULL;

ALTER TABLE `Order` ADD COLUMN `shippingFullName` VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `shippingPhone` VARCHAR(40) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `shippingLine1` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `shippingLine2` VARCHAR(255) NULL;
ALTER TABLE `Order` ADD COLUMN `shippingDistrict` VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `shippingCity` VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `shippingPostalCode` VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `shippingCountry` VARCHAR(2) NOT NULL DEFAULT 'TR';

ALTER TABLE `Order` ADD COLUMN `billingSameAsShipping` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `Order` ADD COLUMN `billingFullName` VARCHAR(200) NULL;
ALTER TABLE `Order` ADD COLUMN `billingPhone` VARCHAR(40) NULL;
ALTER TABLE `Order` ADD COLUMN `billingLine1` VARCHAR(255) NULL;
ALTER TABLE `Order` ADD COLUMN `billingLine2` VARCHAR(255) NULL;
ALTER TABLE `Order` ADD COLUMN `billingDistrict` VARCHAR(120) NULL;
ALTER TABLE `Order` ADD COLUMN `billingCity` VARCHAR(120) NULL;
ALTER TABLE `Order` ADD COLUMN `billingPostalCode` VARCHAR(20) NULL;
ALTER TABLE `Order` ADD COLUMN `billingCountry` VARCHAR(2) NULL;

ALTER TABLE `Order` ADD CONSTRAINT `Order_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
